[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$DestinationRoot,[string]$DestinationDll='',[string]$BaselineDll='D:\Code\How2fish\EnvinciblesMods-CompleteCheatMenu\artifacts\cnkx-port\task17-3-initial-velocity\CompleteCheatMenu.task17-3.zh-CN.dll')
$ErrorActionPreference='Stop';$root=[IO.Path]::GetFullPath($DestinationRoot);if(-not(Test-Path -LiteralPath $root -PathType Container)){throw "DestinationRoot does not exist: $root"};$original=Join-Path $PSScriptRoot 'original'
$files=[ordered]@{
'decompiled-src__CompleteCheatMenu__Runtime__CheatState.cs'='decompiled-src\CompleteCheatMenu\Runtime\CheatState.cs';'decompiled-src__CompleteCheatMenu__Runtime__Presets.cs'='decompiled-src\CompleteCheatMenu\Runtime\Presets.cs';'decompiled-src__CompleteCheatMenu__UI__Tabs__WeaponsTab.cs'='decompiled-src\CompleteCheatMenu\UI\Tabs\WeaponsTab.cs';'decompiled-src__CompleteCheatMenu__UI__Tabs__DiagnosticsTab.cs'='decompiled-src\CompleteCheatMenu\UI\Tabs\DiagnosticsTab.cs';'decompiled-src__CompleteCheatMenu__Plugin.cs'='decompiled-src\CompleteCheatMenu\Plugin.cs';'decompiled-src__CompleteCheatMenu__Targeting__BallisticPredictor.cs'='decompiled-src\CompleteCheatMenu\Targeting\BallisticPredictor.cs';'decompiled-src__CompleteCheatMenu__Targeting__InitialVelocityRedirector.cs'='decompiled-src\CompleteCheatMenu\Targeting\InitialVelocityRedirector.cs';'decompiled-src__CompleteCheatMenu__Patches__WeaponAddProjectile_Patch.cs'='decompiled-src\CompleteCheatMenu\Patches\WeaponAddProjectile_Patch.cs';'decompiled-src__CompleteCheatMenu__Patches__WeaponAddProjectiles_Patch.cs'='decompiled-src\CompleteCheatMenu\Patches\WeaponAddProjectiles_Patch.cs';'tests__ballistic_prediction_test.py'='tests\ballistic_prediction_test.py';'tests__projectile_initial_velocity_harness.cs'='tests\projectile_initial_velocity_harness.cs';'docs__plans__2026-08-25-complete-cheat-menu-cnkx-port-implementation-plan.md'='docs\plans\2026-08-25-complete-cheat-menu-cnkx-port-implementation-plan.md'}
foreach($e in $files.GetEnumerator()){$d=[IO.Path]::GetFullPath((Join-Path $root $e.Value));if(-not$d.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw "Rollback destination escaped root: $d"};New-Item -ItemType Directory -Path(Split-Path -Parent $d)-Force|Out-Null;Copy-Item -LiteralPath(Join-Path $original $e.Key)-Destination $d -Force}
$created=@('decompiled-src\CompleteCheatMenu\Targeting\ProjectileGuidance.cs','decompiled-src\CompleteCheatMenu\Targeting\ProjectileGuidanceMath.cs','decompiled-src\CompleteCheatMenu\Patches\ProjectileUpdateScan_Patch.cs','decompiled-src\CompleteCheatMenu\Patches\ProjectileRemove_Patch.cs','tests\projectile_guidance_test.py','tests\projectile_guidance_harness.cs','tests\projectile_guidance_lifecycle_harness.cs')
foreach($rel in $created){$p=[IO.Path]::GetFullPath((Join-Path $root $rel));if(-not$p.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)){throw "Rollback deletion escaped root: $p"};if(Test-Path -LiteralPath $p -PathType Leaf){Remove-Item -LiteralPath $p -Force}}
if(-not[string]::IsNullOrWhiteSpace($DestinationDll)){$dll=[IO.Path]::GetFullPath($DestinationDll);New-Item -ItemType Directory -Path(Split-Path -Parent $dll)-Force|Out-Null;Copy-Item -LiteralPath $BaselineDll -Destination $dll -Force;Write-Output "RESTORED_DLL_SHA256=$((Get-FileHash $dll -Algorithm SHA256).Hash)"}
Write-Output 'RESTORED_SOURCE_FILES=12';Write-Output "CREATED_FILES_PRESENT=$(@($created|Where-Object{Test-Path -LiteralPath(Join-Path $root $_)-PathType Leaf}).Count)";Write-Output 'ROLLBACK_TASK17_4=PASS'
